spring:
  application:
    name: "post"
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
management:
  endpoint:
    web:
      exposure:
        include: loggers, health, info, mappings
app:
  css-style-location:
  convert-params:
    - ${PANDOC_PATH}
    - "-f"
    - "markdown"
    - "-t"
    - "html"
    - "--toc"
    - "-c"
    - ${CSS_STYLE_LOCATION}
    - "--self-contained" # --self-contained добавляет html заголовок, без него просто будет body
aws.s3:
  endpoint: ${ENDPOINT}
  signer: AWSS3V4SignerType
  access-key: ${ACCESSKEY}
  secret-key: ${SECRETKEY}
  region: ${REGION}
  bucket-source:  ${BUCKETSOURCE}
  bucket-content: ${BUCKETCONTENT}
server:
  port: 9900